import Head from 'next/head';

/**
 * Es una función que devuelve un componente React.
 *
 * El componente React es un fragmento que contiene un encabezado, un principal y un h1.
 *
 * El encabezado contiene un título, una meta descripción, una meta ventana gráfica y un enlace a un
 * favicon.
 *
 * El principal contiene un h1 y un h1.
 *
 * El primer h1 tiene un nombre de clase de text-3xl font-negrita subrayado.
 *
 * El segundo h1 no tiene className.
 *
 * La primera h1 contiene el texto El Asador de Richard.
 *
 * El segundo h1 contiene el texto sobre.
 * @returns Un componente React.
 */
export default function About() {
	return (
		<>
			<Head>
				<title>El Asador de Richard</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<h1 className='text-3xl font-bold underline'>El Asador de Richard</h1>
				<h1>about</h1>
			</main>
		</>
	);
}
