import Head from 'next/head';
import { Inter } from '@next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Contacto() {
	return (
		<>
			<Head>
				<title>El Asador de Richard</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<h1 className='text-3xl font-bold underline'>El Asador de Richard</h1>
				<h1>contacto</h1>
			</main>
		</>
	);
}
