import Head from 'next/head';

/**
 * Devuelve un fragmento de React que contiene un elemento principal con un título, dos metaelementos y
 * un elemento de enlace, seguido de un elemento principal que contiene dos elementos h1.
 * @returns Un componente de reacción
 */
export default function Platillos() {
	return (
		<>
			<Head>
				<title>El Asador de Richard</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<h1 className='text-3xl font-bold underline'>El Asador de Richard</h1>
				<h1>platillos</h1>
			</main>
		</>
	);
}
